-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Cooperative"
(
    cooperative_id bigserial NOT NULL,
    cooperative_name text NOT NULL,
    PRIMARY KEY (cooperative_id)
);

CREATE TABLE IF NOT EXISTS public."Devices"
(
    device_id bigserial NOT NULL,
    cooperative_id bigserial NOT NULL,
    PRIMARY KEY (device_id)
);

CREATE TABLE IF NOT EXISTS public."Materials"
(
    "Material_id" bigserial NOT NULL,
    "Material_name" text NOT NULL,
    "Material_group" bigserial,
    PRIMARY KEY ("Material_id")
);

CREATE TABLE IF NOT EXISTS public."Groups"
(
    "Group_id" bigserial NOT NULL,
    "Group_name" text NOT NULL,
    PRIMARY KEY ("Group_id")
);

CREATE TABLE IF NOT EXISTS public."Sales"
(
    "Sale_id" bigserial NOT NULL,
    "Date" date NOT NULL,
    "Material" bigserial NOT NULL,
    "Weight" numeric(10, 2) NOT NULL,
    "Price_Kg" numeric(10, 2) NOT NULL,
    "Buyer" bigserial NOT NULL,
    "Responsible" bigserial NOT NULL,
    PRIMARY KEY ("Sale_id")
);

CREATE TABLE IF NOT EXISTS public."Buyers"
(
    "Buyer_id" bigserial NOT NULL,
    "Buyer_name" text NOT NULL,
    PRIMARY KEY ("Buyer_id")
);

CREATE TABLE IF NOT EXISTS public."Workers"
(
    "Worker_id" bigserial NOT NULL,
    "Worker_name" text NOT NULL,
    "Cooperative" bigserial NOT NULL,
    "CPF" bytea NOT NULL,
    "User_type" "char" NOT NULL,
    "Birth_date" date NOT NULL,
    "Enter_date" date NOT NULL,
    "Exit_date" date,
    "PIS" bytea NOT NULL,
    "RG" bytea NOT NULL,
    "Gender" text,
    "Password" bytea NOT NULL,
    "Email" text NOT NULL,
    "Last_update" date,
    PRIMARY KEY ("Worker_id")
);

CREATE TABLE IF NOT EXISTS public."Measurments"
(
    "Weighting_id" bigserial NOT NULL,
    "Weight_KG" numeric(10, 2) NOT NULL,
    "Time_stamp" date NOT NULL,
    "Wastepicker" bigserial NOT NULL,
    "Material" bigserial NOT NULL,
    "Device" bigserial NOT NULL,
    "Bag_filled" boolean NOT NULL,
    PRIMARY KEY ("Weighting_id")
);

CREATE TABLE IF NOT EXISTS public."Stock"
(
    "Stock_id" bigserial NOT NULL,
    "Cooperative" bigserial NOT NULL,
    "Material" bigserial NOT NULL,
    "Total_collected_KG" numeric(900, 2) NOT NULL,
    "Total_sold_KG" numeric(900, 2) NOT NULL,
    "Current_stock_KG" numeric(45, 2) NOT NULL,
    PRIMARY KEY ("Stock_id")
);

CREATE TABLE IF NOT EXISTS public."Worker_contributions"
(
    "Contribution_id" bigserial NOT NULL,
    "Wastepicker" bigserial NOT NULL,
    "Material" bigserial NOT NULL,
    cooperative bigserial NOT NULL,
    "Period" daterange NOT NULL,
    "Weight_KG" numeric(15, 2) NOT NULL,
    "Last_updated" date,
    PRIMARY KEY ("Contribution_id")
);

ALTER TABLE IF EXISTS public."Devices"
    ADD CONSTRAINT "Cooperative_id" FOREIGN KEY (cooperative_id)
    REFERENCES public."Cooperative" (cooperative_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Materials"
    ADD CONSTRAINT "Material_group" FOREIGN KEY ("Material_group")
    REFERENCES public."Groups" ("Group_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Sales"
    ADD CONSTRAINT "Material" FOREIGN KEY ("Material")
    REFERENCES public."Materials" ("Material_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Sales"
    ADD CONSTRAINT "Buyer" FOREIGN KEY ("Buyer")
    REFERENCES public."Buyers" ("Buyer_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Sales"
    ADD CONSTRAINT "Responsible" FOREIGN KEY ("Responsible")
    REFERENCES public."Workers" ("Worker_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Workers"
    ADD CONSTRAINT cooperative FOREIGN KEY ("Cooperative")
    REFERENCES public."Cooperative" (cooperative_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Measurments"
    ADD CONSTRAINT wastepicker FOREIGN KEY ("Wastepicker")
    REFERENCES public."Workers" ("Worker_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Measurments"
    ADD CONSTRAINT "Material" FOREIGN KEY ("Material")
    REFERENCES public."Materials" ("Material_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Measurments"
    ADD CONSTRAINT "Device" FOREIGN KEY ("Device")
    REFERENCES public."Devices" (device_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Stock"
    ADD CONSTRAINT "Cooperative" FOREIGN KEY ("Cooperative")
    REFERENCES public."Cooperative" (cooperative_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Stock"
    ADD CONSTRAINT "Material" FOREIGN KEY ("Material")
    REFERENCES public."Materials" ("Material_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Worker_contributions"
    ADD CONSTRAINT "Wastepicker" FOREIGN KEY ("Wastepicker")
    REFERENCES public."Workers" ("Worker_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Worker_contributions"
    ADD CONSTRAINT "Cooperative" FOREIGN KEY (cooperative)
    REFERENCES public."Cooperative" (cooperative_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Worker_contributions"
    ADD CONSTRAINT "Material" FOREIGN KEY ("Material")
    REFERENCES public."Materials" ("Material_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;